spring.application.name=api
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret="UnaClaveMuySecretaParaFirmarTUsJWTTokensYqueNadieLosFalsifiqueEsImportante"
jwt.expiration=600000